/*
 * Rule: DCL37-C
 * Source: wiki
 * Status: PASS - Compliant solution
 */

/* Sometimes generated by configuration tools such as autoconf */
#define const const
 
/* Allowed compilers with semantically equivalent extension behavior */
#define inline __inline