use std::fs::{self, File};
use std::io::Write;
use std::path::PathBuf;
use walkdir::WalkDir;

fn main() {
    // Only compile resources on Windows
    #[cfg(target_os = "windows")]
    {
        let mut res = winres::WindowsResource::new();
        res.set_icon("icon.ico");
        res.compile().unwrap();
    }

    // Generate rules-all.toml from individual RULE-ID.toml files
    generate_rules_all_toml();

    // Generate integration tests from C test files
    generate_integration_tests();
}

fn generate_rules_all_toml() {
    let rules_dir = PathBuf::from("src/rules");

    // Find all ruleset directories (direct children of src/rules/)
    let rulesets: Vec<PathBuf> = match fs::read_dir(&rules_dir) {
        Ok(entries) => entries
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.is_dir())
            .collect(),
        Err(e) => {
            eprintln!("Warning: Could not read src/rules directory: {}", e);
            return;
        }
    };

    // Process each ruleset
    for ruleset_dir in rulesets {
        let ruleset_name = ruleset_dir.file_name().unwrap().to_string_lossy();
        let output_path = ruleset_dir.join("rules-all.toml");

        // Collect all RULE-ID.toml files in this ruleset
        let mut toml_files: Vec<PathBuf> = WalkDir::new(&ruleset_dir)
            .into_iter()
            .filter_map(|e| e.ok())
            .filter(|e| {
                e.path().is_file()
                    && e.path().extension().map_or(false, |ext| ext == "toml")
                    && e.path()
                        .file_name()
                        .map_or(false, |name| {
                            let name_str = name.to_string_lossy();
                            // Match pattern like ARR30-C.toml, but exclude rules-all.toml
                            name_str != "rules-all.toml"
                                && name_str.contains('-')
                                && !name_str.starts_with('.')
                        })
            })
            .map(|e| e.path().to_path_buf())
            .collect();

        if toml_files.is_empty() {
            println!("No rule manifests found in ruleset: {}", ruleset_name);
            continue;
        }

        // Sort by rule ID for consistent output
        toml_files.sort();

        // Combine all TOML files
        let mut combined_content = String::new();
        combined_content.push_str("# Auto-generated file - do not edit directly\n");
        combined_content.push_str(&format!("# Generated from individual rule manifests in {}\n", ruleset_name));
        combined_content.push_str("# To modify, edit the individual TOML files and rebuild\n\n");

        for toml_path in &toml_files {
            // Add source comment
            let relative_path = toml_path
                .strip_prefix(&ruleset_dir)
                .unwrap_or(toml_path);
            combined_content.push_str(&format!("# Source: {}\n", relative_path.display()));

            // Read and append content
            match fs::read_to_string(toml_path) {
                Ok(content) => {
                    combined_content.push_str(&content);
                    if !content.ends_with('\n') {
                        combined_content.push('\n');
                    }
                    combined_content.push('\n');
                }
                Err(e) => {
                    eprintln!("Warning: Failed to read {}: {}", toml_path.display(), e);
                }
            }
        }

        // Write combined file
        match File::create(&output_path) {
            Ok(mut file) => {
                if let Err(e) = file.write_all(combined_content.as_bytes()) {
                    eprintln!("Error writing {}: {}", output_path.display(), e);
                } else {
                    println!("cargo:rerun-if-changed={}", ruleset_dir.display());
                    println!("Generated {} rules-all.toml with {} rule manifests",
                             ruleset_name, toml_files.len());
                }
            }
            Err(e) => {
                eprintln!("Error creating {}: {}", output_path.display(), e);
            }
        }
    }
}

fn generate_integration_tests() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = PathBuf::from(&out_dir).join("integration_tests.rs");
    let mut f = File::create(&dest_path).expect("Failed to create integration_tests.rs");

    // Write file header
    writeln!(f, "// Auto-generated integration tests").unwrap();
    writeln!(f, "// DO NOT EDIT - Generated by build.rs\n").unwrap();
    writeln!(f, "use crate::parser::CParser;").unwrap();
    writeln!(f, "use crate::rules::{{CertRule, RuleRegistry}};").unwrap();
    writeln!(f, "use std::path::Path;\n").unwrap();

    let cert_c_dir = PathBuf::from("src/rules/cert_c");

    // Walk through CATEGORY directories
    for category_entry in fs::read_dir(&cert_c_dir).unwrap() {
        let category_entry = category_entry.unwrap();
        let category_path = category_entry.path();

        if !category_path.is_dir() {
            continue;
        }

        let category_name = category_path.file_name().unwrap().to_str().unwrap();

        // Skip special directories
        if category_name == "tests" || category_name == "utils" || category_name.starts_with('.') {
            continue;
        }

        // Walk through RULE-ID directories
        for rule_entry in fs::read_dir(&category_path).unwrap() {
            let rule_entry = rule_entry.unwrap();
            let rule_path = rule_entry.path();

            if !rule_path.is_dir() {
                continue;
            }

            let rule_id = rule_path.file_name().unwrap().to_str().unwrap();
            let tests_dir = rule_path.join("tests");

            if !tests_dir.exists() {
                continue;
            }

            // Generate tests for fail/ directory
            let fail_dir = tests_dir.join("fail");
            if fail_dir.exists() {
                for test_file in fs::read_dir(&fail_dir).unwrap() {
                    let test_file = test_file.unwrap();
                    let test_path = test_file.path();

                    if test_path.extension().map_or(false, |e| e == "c") {
                        generate_test_function(
                            &mut f,
                            rule_id,
                            category_name,
                            &test_path,
                            "fail"
                        );
                    }
                }
            }

            // Generate tests for pass/ directory
            let pass_dir = tests_dir.join("pass");
            if pass_dir.exists() {
                for test_file in fs::read_dir(&pass_dir).unwrap() {
                    let test_file = test_file.unwrap();
                    let test_path = test_file.path();

                    if test_path.extension().map_or(false, |e| e == "c") {
                        generate_test_function(
                            &mut f,
                            rule_id,
                            category_name,
                            &test_path,
                            "pass"
                        );
                    }
                }
            }
        }
    }

    println!("cargo:rerun-if-changed=src/rules/cert_c");
}

fn generate_test_function(
    f: &mut File,
    rule_id: &str,
    category: &str,
    test_path: &std::path::Path,
    test_type: &str  // "fail" or "pass"
) {
    // Convert rule_id to snake_case for function name
    let rule_snake = rule_id.to_lowercase().replace('-', "_");

    // Get test file name without extension
    let test_file_stem = test_path.file_stem().unwrap().to_str().unwrap();
    let test_name_safe = test_file_stem.replace('-', "_").replace('.', "_");

    // Generate test function name: test_arr00_c_fail_wiki_noncompliant_1
    let test_fn_name = format!("test_{}_{}_{}",  rule_snake, test_type, test_name_safe);

    // Get relative path from project root
    let relative_path = format!("src/rules/cert_c/{}/{}/tests/{}/{}",
        category, rule_id, test_type, test_path.file_name().unwrap().to_str().unwrap());

    // Check if rule is implemented by reading the TOML file
    let toml_path = format!("src/rules/cert_c/{}/{}/{}.toml", category, rule_id, rule_id);
    let is_enabled = check_if_rule_enabled(&toml_path);

    writeln!(f, "#[test]").unwrap();

    // If rule is not enabled/implemented, mark test as ignored
    if !is_enabled {
        writeln!(f, "#[ignore = \"Rule {} not yet implemented\"]", rule_id).unwrap();
    }
    writeln!(f, "fn {}() {{", test_fn_name).unwrap();
    writeln!(f, "    let registry = RuleRegistry::new();").unwrap();
    writeln!(f, "    let rule = registry.get_rule(\"{}\").expect(\"Rule {} not found in registry\");",
        rule_id, rule_id).unwrap();
    writeln!(f, "    ").unwrap();
    writeln!(f, "    let test_path = Path::new(env!(\"CARGO_MANIFEST_DIR\")).join(\"{}\");",
        relative_path).unwrap();
    writeln!(f, "    let source = std::fs::read_to_string(&test_path)").unwrap();
    writeln!(f, "        .unwrap_or_else(|e| panic!(\"Failed to read {{:?}}: {{}}\", test_path, e));").unwrap();
    writeln!(f, "    ").unwrap();
    writeln!(f, "    let mut parser = CParser::new().expect(\"Failed to create parser\");").unwrap();
    writeln!(f, "    let tree = parser.parse_source(&source)").unwrap();
    writeln!(f, "        .unwrap_or_else(|e| panic!(\"Failed to parse {{:?}}: {{}}\", test_path, e));").unwrap();
    writeln!(f, "    ").unwrap();
    writeln!(f, "    let violations = rule.check(&tree.root_node(), &source);").unwrap();
    writeln!(f, "    ").unwrap();

    if test_type == "fail" {
        writeln!(f, "    assert!(").unwrap();
        writeln!(f, "        !violations.is_empty(),").unwrap();
        writeln!(f, "        \"[{}] Expected violation in {{:?}} but found none\",", rule_id).unwrap();
        writeln!(f, "        test_path.file_name().unwrap()").unwrap();
        writeln!(f, "    );").unwrap();
    } else {
        writeln!(f, "    assert!(").unwrap();
        writeln!(f, "        violations.is_empty(),").unwrap();
        writeln!(f, "        \"[{}] Unexpected violation in {{:?}}: {{}}\",", rule_id).unwrap();
        writeln!(f, "        test_path.file_name().unwrap(),").unwrap();
        writeln!(f, "        violations.first().map(|v| &v.message).unwrap_or(&String::from(\"unknown\"))").unwrap();
        writeln!(f, "    );").unwrap();
    }

    writeln!(f, "}}").unwrap();
    writeln!(f).unwrap();
}

fn check_if_rule_enabled(toml_path: &str) -> bool {
    // Read the TOML file and check if rule is enabled
    match fs::read_to_string(toml_path) {
        Ok(content) => {
            // Check for implemented rule format: [rules.cert_c.RULE-ID] enabled = true
            if content.contains("[rules.cert_c.") && content.contains("enabled = true") {
                return true;
            }

            // Check for unimplemented rule format: [rule] enabled = false
            if content.contains("[rule]") && content.contains("enabled = false") {
                return false;
            }

            // Default to false if format is unclear
            false
        }
        Err(_) => false, // If TOML file doesn't exist, assume not implemented
    }
}
