[metadata]
id = "DCL20-C"
type = "recommendation"
category = "DCL"
number = 20
title = "Explicitly specify void when a function accepts no arguments"
description = """
According to the C Standard, subclause 6.7.6.3, paragraph 14 [ISO/IEC
9899:2011], Subclause 6.11.6 states that Consequently, functions that accept no
arguments should explicitly declare avoidparameter in their parameter list. This
holds true in both the declaration and definition sections (which should match).
"""
severity = "Medium"
likelihood = "Probable"
priority = "P12"
level = "L1"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 19, 2025"

[rules.cert_c.DCL20-C]
enabled = false

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/DCL20-C.+Explicitly+specify+void+when+a+function+accepts+no+arguments"
