[metadata]
id = "DCL16-C"
type = "recommendation"
category = "DCL"
number = 16
title = "Use "L," not "l," to indicate a long value"
description = """
Lowercase letterl(ell) can easily be confused with the digit1(one). This can be
particularly confusing when indicating that an integer literal constant is a
long value. This recommendation is similar toDCL02-C. Use visually distinct
identifiers. Likewise, you should use uppercaseLLrather than lowercasellwhen
indicating that an integer literal constant is along longvalue. To be precise
when using modifiers to indicate the type of an integer literal, the first
character may not bel. It may beL,u, orU. Subsequent characters have no strict
case requirements. This noncompliant example highlights the result of adding an
integer and a long value even though it appears that two integers1111are being
added:
"""
severity = "Low"
likelihood = "Unlikely"
priority = "P3"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "Unknown"

[rules.cert_c.DCL16-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152241"
