[metadata]
id = "DCL23-C"
type = "recommendation"
category = "DCL"
number = 23
title = "Guarantee that mutually visible identifiers are unique"
description = """
According to subclause 6.2.7 of the C Standard [ISO/IEC 9899:2011], (See
alsoundefined behavior 14of Annex J.) Further, according to subclause 6.4.2.1,
"""
severity = "Medium"
likelihood = "Unlikely"
priority = "P6"
level = "L2"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 19, 2025"

[rules.cert_c.DCL23-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/DCL23-C.+Guarantee+that+mutually+visible+identifiers+are+unique"
