[metadata]
id = "MSC25-C"
type = "recommendation"
category = "MSC"
number = 25
title = 'Do not use insecure or weak cryptographic algorithms'
description = '''
This rule is a stub.
'''
severity = "Medium"
likelihood = "Probable"
priority = "P4"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "Unknown"

[rules.cert_c.MSC25-C]
enabled = false

[references]
wiki = "https://cmu-sei.github.io/secure-coding-standards/sei-cert-c-coding-standard/recommendations/miscellaneous-msc/msc25-c"
cwe = []
