[metadata]
id = "FLP38-C"
type = "rule"
category = "FLP"
number = 38
title = 'Avoid undefined behavior while using type-generic macro functions'
description = '''
Section 7.27 of [ ISO/IEC 9899:2024 ] provides the headers <tgmath.h>, <math.h>
and <complex.h> and provides type-generic macros. Many of these are designed to
work on complex numbers or various types of floating-point numbers. However,
there are many ways to misuse these functions, which can lead to undefined
behaviors 203, 204, 206, and 207.
'''
severity = "Low"
likelihood = "Unlikely"
priority = "P3"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "Unknown"

[rules.cert_c.FLP38-C]
enabled = true

[references]
wiki = "https://cmu-sei.github.io/secure-coding-standards/sei-cert-c-coding-standard/rules/floating-point-flp/flp38-c"
cwe = []
