[metadata]
id = "EXP42-C"
type = "rule"
category = "EXP"
number = 42
title = "Do not compare padding data"
description = """
The C Standard, 6.7.3.2 paragraph 19 [ISO/IEC 9899:2024], states Subclause
6.7.11, paragraph 10, states that The only exception is that padding bits are
set to zero when a static or thread-local object is implicitly initialized
(paragraph 11):
"""
severity = "Medium"
likelihood = "Probable"
priority = "P12"
level = "L1"
cert_version = "2016 Edition (Wiki)"
last_modified = "May 05, 2025"

[rules.cert_c.EXP42-C]
enabled = false

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/EXP42-C.+Do+not+compare+padding+data"
