#!/usr/bin/env bash
# Bound cargo target/ growth on disk-constrained dev nodes.
#
# Two independent knobs, both conservative:
#   1. cargo-sweep prunes artifacts not touched in $SWEEP_DAYS days. Safe:
#      anything it removes is regenerated by the next build that needs it.
#   2. target/debug/incremental is deleted outright once target/ exceeds
#      $MAX_TARGET_GB. It is a pure cache -- deleting it costs one slower
#      rebuild, nothing else -- and it is the dominant grower. Measured on
#      dev-180 (tools_sqc, clean tree): `cargo build` alone leaves
#      target/debug at 868M, 372M of it incremental; one `cargo test
#      --no-run` on top takes it to 2.4G, 1.6G of it incremental.
#   3. If a repo is STILL over $MAX_TARGET_GB after (1) and (2), its whole
#      dev profile is cleaned. target/release is never touched at any
#      stage -- benchmarks run against target/release/sqc and a run must
#      not be disturbed mid-flight (see CLAUDE.md).
#
# Never runs while a build is in flight: cargo would race the deletion.
# Two guards, because neither covers the other -- a process check cannot
# tell which repo a running cargo is building, and a repo's lock file says
# nothing about a build that has not taken it yet.
#
# Usage: cargo-target-gc.sh [repo ...]   (default: the repos listed below)
set -uo pipefail

SWEEP_DAYS="${SWEEP_DAYS:-7}"
MAX_TARGET_GB="${MAX_TARGET_GB:-6}"
REPOS=("$@")
if [ ${#REPOS[@]} -eq 0 ]; then
  REPOS=(
    "$HOME/data-enterprise/tools_sqc"
    "$HOME/data-enterprise/todo-sqlite-cli"
    "$HOME/data-enterprise/knots"
    "$HOME/data-enterprise/lang_parsing_substrate"
  )
fi

if pgrep -x cargo >/dev/null || pgrep -x rustc >/dev/null; then
  echo "$(date -Is) skip: a cargo/rustc build is running"
  exit 0
fi

for repo in "${REPOS[@]}"; do
  [ -d "$repo/target" ] || continue

  # Cargo holds an exclusive flock on target/<profile>/.cargo-lock for the
  # duration of a build. Skip just this repo rather than race it.
  lock="$repo/target/debug/.cargo-lock"
  if [ -f "$lock" ] && ! flock -n "$lock" true; then
    echo "$(date -Is) skip $repo: a build holds $lock"
    continue
  fi

  before=$(du -sm "$repo/target" | cut -f1)

  if command -v cargo-sweep >/dev/null; then
    (cd "$repo" && cargo sweep --time "$SWEEP_DAYS" >/dev/null 2>&1)
  fi

  now=$(du -sm "$repo/target" | cut -f1)
  if [ "$now" -gt $((MAX_TARGET_GB * 1024)) ]; then
    rm -rf "$repo/target/debug/incremental"
    now=$(du -sm "$repo/target" | cut -f1)
  fi

  if [ "$now" -gt $((MAX_TARGET_GB * 1024)) ]; then
    (cd "$repo" && cargo clean --profile dev >/dev/null 2>&1)
    now=$(du -sm "$repo/target" | cut -f1)
  fi

  echo "$(date -Is) $repo: ${before}M -> ${now}M"
done
