#!/usr/bin/env python3
"""Assert the docs' rule counts match rules_templates/rules-all.toml.

WHY THIS EXISTS

On 2026-09-03 eight files claimed a rule count and they gave three different
answers: README.md said 307 enabled / 311 implemented (correct),
docs/index.rst said 305 enabled, docs/configuration.rst and
docs/project-structure.rst said 306, docs/architecture.rst and
docs/testing-methodology.rst said 305, and docs/test-summary.md's generator
counted ENABLED rules under a heading reading "Implemented Rules", which is
where the confusion started -- 307 and 311 are both right, for different
questions, and the generated doc used the wrong word for one of them.

Nothing noticed, because the enabled count moves whenever a rule is toggled
in the default manifest and no doc is regenerated when it does. This is the
same failure mode README's BENCH:HIGHLIGHTS marker block solves for benchmark
figures: a number in prose goes stale silently.

WHAT IT CHECKS

Two numbers, derived from the manifest itself:

    implemented  every [rules.cert_c.<ID>] block          (311)
    enabled      those blocks with `enabled = true`        (307)

Then every phrasing in the docs that claims one of them. A claim of some
OTHER number fails, naming the file and line. Counts that are legitimately
neither -- test-fixture directory totals, test-case totals, per-category
figures -- are not matched by these patterns and are left alone.

Deliberately NOT a check that the two numbers have particular values: the
manifest is the source of truth, so enabling a rule should require no edit
here. It requires an edit to the docs, which is the point.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "rules_templates" / "rules-all.toml"

# Files that make a rule-count claim. docs/test-summary.md is generated by
# src/rules/cert_c/integration.rs, so it is checked too -- if it disagrees,
# the generator is wrong and regenerating will not help.
TARGETS = [
    "README.md",
    "docs/index.rst",
    "docs/configuration.rst",
    "docs/architecture.rst",
    "docs/project-structure.rst",
    "docs/testing-methodology.rst",
    "docs/benchmark-running.rst",
    "docs/bibliography.rst",
    "docs/interactive-ui.rst",
    "docs/tool-comparison.rst",
    "docs/test-summary.md",
]

# Each pattern must capture the number in group 1. Kept narrow on purpose:
# a pattern that matches too much turns this check into noise and gets
# disabled, which is worse than not having it.
ENABLED_PATTERNS = [
    r"(\d{3})\s+(?:CERT C\s+)?rules?\s+enabled by default",
    r"enables?\s+(\d{3})\s+of the \d{3} implemented rules",
    r"\((\d{3})\s+enabled by default\)",
    r"all\s+(\d{3})\s+enabled rules",
    r"#\s*(\d{3})\s+of \d{3} rules enabled",
    r"-->\s*(\d{3})\s+CERT C rules applied",
    r"\*\*Enabled By Default:\*\*\s+(\d{3})",
    r"(\d{3})\s+enabled\s*/\s*\d+\s+implemented",
    r"rules,\s+(\d{3})\s+enabled by default",
]
IMPLEMENTED_PATTERNS = [
    r"(\d{3})\s+rules? (?:are )?implemented",
    r"\((\d{3})\s+implemented\)",
    r"implements\s+(\d{3})\s+rules",
    r"of the (\d{3}) implemented rules",
    r"\*\*Implemented Rules:\*\*\s+(\d{3})",
    r"(\d{3})\s+CERT C rules across 17 categories",
    r"(\d{3})\s+rules across 17 categories",
    r"\*\*(\d{3})\s+rules\*\*, 17 categories",
    r"(\d{3})\s+rules by category",
    r"^\s+-\s+(\d{3})\s+implemented$",
]


def manifest_counts(text: str) -> tuple[int, int]:
    blocks = re.findall(
        r"^\[rules\.cert_c\.([A-Z]+[0-9]+-C)\]\n((?:(?!^\[).*\n)*)", text, re.M)
    if not blocks:
        raise SystemExit(f"no [rules.cert_c.*] blocks found in {MANIFEST}")
    enabled = sum(
        1 for _, body in blocks
        if re.search(r"^\s*enabled\s*=\s*true", body, re.M))
    return len(blocks), enabled


def main() -> int:
    implemented, enabled = manifest_counts(MANIFEST.read_text())
    print(f"{MANIFEST.relative_to(ROOT)}: "
          f"{implemented} implemented, {enabled} enabled by default")

    bad = []
    checked = 0
    for rel in TARGETS:
        path = ROOT / rel
        if not path.is_file():
            continue
        for lineno, line in enumerate(path.read_text().splitlines(), 1):
            for pats, expect, what in (
                    (ENABLED_PATTERNS, enabled, "enabled"),
                    (IMPLEMENTED_PATTERNS, implemented, "implemented")):
                for pat in pats:
                    for m in re.finditer(pat, line, re.M):
                        checked += 1
                        got = int(m.group(1))
                        if got != expect:
                            bad.append((rel, lineno, what, got, expect,
                                        line.strip()[:96]))
    if bad:
        print(f"\n{len(bad)} stale rule count(s):\n")
        for rel, lineno, what, got, expect, ctx in bad:
            print(f"  {rel}:{lineno}  says {got} {what}, manifest says {expect}")
            print(f"      {ctx}")
        print("\nThe manifest is the source of truth. Update the docs, or "
              "-- if docs/test-summary.md is listed above -- fix\n"
              "src/rules/cert_c/integration.rs and re-run "
              "`cargo test --package aurora-lint --lib -- rules::cert_c`.")
        return 1
    print(f"{checked} rule-count claim(s) across "
          f"{len(TARGETS)} file(s): all consistent")
    return 0


if __name__ == "__main__":
    sys.exit(main())
