#!/usr/bin/env python3
"""Generate CHANGELOG.md (Keep a Changelog format) from the task database.

The project does not hand-write release notes: every shipped change is already
a done task in `todo-sqlite-cli.db`, and every published release is an
annotated `v*` git tag. This script joins the two -- tasks completed between
two tags become that release's section -- so the changelog is a projection of
records that already exist rather than a second thing to keep current.

Version numbers here are *published releases*, not every version the crate
passed through. sqc bumps the patch version on nearly every commit (`run_id`
discriminates benchmark runs by SHA, see CLAUDE.md), so most versions are
never tagged and never shipped; a release section therefore covers everything
completed since the previous tag.

Usage:
    python3 scripts/generate_changelog.py                  # rewrite CHANGELOG.md
    python3 scripts/generate_changelog.py --check          # exit 1 if stale
    python3 scripts/generate_changelog.py --release 0.4.315  # one section, to stdout
"""
import argparse
import re
import sqlite3
import subprocess
import sys
from collections import OrderedDict
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DB_PATH = REPO_ROOT / "todo-sqlite-cli.db"
CHANGELOG_PATH = REPO_ROOT / "CHANGELOG.md"

# Keep a Changelog buckets, in precedence order: a task is filed under the
# first bucket any of its tags matches. The `added`/`changed`/`fixed` tags were
# an explicit changelog convention that lapsed after 2026-04, so the modern
# tag vocabulary (rule-bug, fp-reduction, new-rule, ...) is mapped too --
# without that, every section after April 2026 comes back empty.
BUCKETS = OrderedDict([
    ("Added", {"added", "new-rule", "feature", "enhancement"}),
    ("Fixed", {
        "fixed", "bug", "rule-bug", "fp-reduction", "crash", "robustness",
        "parser-gotcha", "rule-hardening", "security", "coverage-gap",
        "fn-detection", "recall",
    }),
    ("Changed", {
        "changed", "refactor", "rule-improvement", "performance", "packaging",
        "infra", "infrastructure", "build", "tech-debt", "architecture",
        "tooling", "knots", "release", "parsing", "analysis", "vra",
        "macro-expansion",
    }),
    ("Documentation", {"documentation", "docs"}),
])

# Work that never ships in the binary: adjudicating findings into ground
# truth, corpus curation, paper drafting. These now belong to the
# `benchmarking_db` and `sqc_paper` backlogs (CLAUDE.md), but their completed
# history stayed in this DB, and they routinely carry a rule tag too -- so
# they are excluded outright rather than only when every tag is internal.
NEVER_SHIPPED = {
    "ground-truth", "ground-truth-quality", "adjudication",
    "delta-adjudication", "evaluation", "paper", "benchmarking-db",
    "external-review",
}

# Measurement and process work: excluded only when the task carries nothing
# else, so a bench-tooling fix that is also tagged `rule-bug` still appears.
INTERNAL_ONLY = {
    "benchmark", "bench", "realworld", "results", "research", "triage",
    "ingest", "task", "deferred", "sqlite-audit-followup", "scraper",
}

HEADER = """# Changelog

All notable changes to sqc are documented here. The format follows
[Keep a Changelog](https://keepachangelog.com/en/1.1.0/).

**Versions here are published releases**, not every version the crate passed
through. sqc bumps the patch version on nearly every commit, and only tagged
versions are built, signed and published; a section therefore covers every
change since the previous release, not since the previous version number.

This file is generated by `scripts/generate_changelog.py` from the project's
task database. Edit a task, not this file -- a hand edit is overwritten on the
next regeneration, and CI checks the two agree.
"""


def run_git(*args):
    return subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args],
        check=True, capture_output=True, text=True,
    ).stdout.strip()


def version_key(v):
    return tuple(int(p) for p in re.findall(r"\d+", v))


def released_versions():
    """Every published release, oldest first, as (version, tag, iso_date)."""
    out = []
    for tag in run_git("tag", "--list", "v*").splitlines():
        tag = tag.strip()
        if not re.fullmatch(r"v\d+\.\d+\.\d+", tag):
            continue
        date = run_git("log", "-1", "--format=%cI", tag)
        out.append((tag[1:], tag, date))
    out.sort(key=lambda r: version_key(r[0]))
    return out


def current_version():
    text = (REPO_ROOT / "Cargo.toml").read_text()
    m = re.search(r'^version\s*=\s*"([^"]+)"', text, re.M)
    if not m:
        raise SystemExit("could not read version from Cargo.toml")
    return m.group(1)


def load_tasks():
    con = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    rows = con.execute(
        "SELECT uuid, title, completed_at FROM tasks "
        "WHERE status = 'done' AND completed_at IS NOT NULL"
    ).fetchall()
    tags = {}
    for uuid, tag in con.execute("SELECT task_uuid, tag FROM tags"):
        tags.setdefault(uuid, set()).add(tag)
    con.close()
    tasks = []
    for uuid, title, completed_at in rows:
        tasks.append((completed_at, title.strip(), tags.get(uuid, set())))
    tasks.sort()
    return tasks


def bucket_for(task_tags):
    if task_tags & NEVER_SHIPPED:
        return None
    for name, members in BUCKETS.items():
        if task_tags & members:
            return name
    if task_tags and task_tags <= INTERNAL_ONLY:
        return None
    # Untagged or an unrecognised area tag (e.g. a bare rule id like `int32-c`):
    # a completed task that shipped something, with no signal about what kind.
    return "Changed"


def sections_for(tasks):
    grouped = OrderedDict((name, []) for name in BUCKETS)
    for _, title, task_tags in tasks:
        name = bucket_for(task_tags)
        if name is not None:
            grouped[name].append(title)
    return OrderedDict((k, v) for k, v in grouped.items() if v)


def render_release(version, date, tasks, *, unreleased=False):
    heading = "## [Unreleased]" if unreleased else f"## [{version}] - {date}"
    lines = [heading, ""]
    sections = sections_for(tasks)
    if not sections:
        lines += ["_No user-visible changes; see the commit log for internal work._", ""]
        return lines
    for name, titles in sections.items():
        lines.append(f"### {name}")
        lines.append("")
        for title in titles:
            lines.append(f"- {escape_bullet(title)}")
        lines.append("")
    return lines


def escape_bullet(title):
    # Task titles are prose, not markdown; keep them readable without letting a
    # stray backtick or underscore reflow the list.
    return title.replace("\n", " ").strip()


def build(tasks, releases, unreleased_version):
    parts = [HEADER.rstrip(), ""]
    prev_date = None
    windows = []
    for version, _tag, date in releases:
        windows.append((version, date, prev_date, date))
        prev_date = date
    last_release_date = releases[-1][2] if releases else None

    pending = [t for t in tasks if last_release_date is None or t[0] > last_release_date]
    if pending:
        parts += render_release(unreleased_version, None, pending, unreleased=True)

    for version, date, lo, hi in reversed(windows):
        window = [t for t in tasks if (lo is None or t[0] > lo) and t[0] <= hi]
        parts += render_release(version, date[:10], window)

    parts += compare_links(releases, unreleased_version, bool(pending))
    return "\n".join(parts).rstrip() + "\n"


def compare_links(releases, unreleased_version, has_pending):
    base = "https://github.com/brandon-arrendondo/tools_sqc"
    lines = []
    if has_pending and releases:
        lines.append(f"[Unreleased]: {base}/compare/{releases[-1][1]}...HEAD")
    for i, (version, tag, _date) in enumerate(reversed(releases)):
        older = releases[len(releases) - i - 2] if i + 2 <= len(releases) else None
        if older:
            lines.append(f"[{version}]: {base}/compare/{older[1]}...{tag}")
        else:
            lines.append(f"[{version}]: {base}/releases/tag/{tag}")
    return ([""] + lines) if lines else []


def extract_section(text, version):
    """Return just the `## [version]` section body, for release notes."""
    pattern = re.compile(
        rf"^## \[{re.escape(version)}\][^\n]*\n(.*?)(?=^## \[|\Z)",
        re.M | re.S,
    )
    m = pattern.search(text)
    return m.group(1).strip() if m else None


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if CHANGELOG.md differs from what would be generated")
    ap.add_argument("--release", metavar="VERSION",
                    help="print only that release's section (release-notes body)")
    ap.add_argument("--output", type=Path, default=CHANGELOG_PATH)
    args = ap.parse_args()

    content = build(load_tasks(), released_versions(), current_version())

    if args.release:
        # Built from the DB and the tags present right now rather than read out
        # of the committed file, so release notes cannot be stale even if
        # CHANGELOG.md was last regenerated some tasks ago.
        version = args.release.lstrip("v")
        body = extract_section(content, version)
        if body is None:
            print(
                f"error: no changelog section for {version}. Tag {version} must "
                "exist and have completed tasks behind it.",
                file=sys.stderr,
            )
            return 1
        print(body)
        return 0

    if args.check:
        existing = args.output.read_text() if args.output.exists() else ""
        if existing != content:
            print(
                f"{args.output.name} is out of date. "
                "Regenerate with: python3 scripts/generate_changelog.py",
                file=sys.stderr,
            )
            return 1
        return 0

    args.output.write_text(content)
    print(f"wrote {args.output} ({content.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
