[metadata]
id = "FLP32-C"
type = "rule"
category = "FLP"
number = 32
title = "Prevent or detect domain and range errors in math functions"
description = """
The C Standard, 7.12.1 [ISO/IEC 9899:2024], defines three types of errors that
relate specifically to math functions in<math.h>. Paragraph 2 states Paragraph 3
states Paragraph 4 states
"""
severity = "Medium"
likelihood = "Probable"
priority = "P12"
level = "L1"
cert_version = "2016 Edition (Wiki)"
last_modified = "Aug 06, 2025"

[rules.cert_c.FLP32-C]
enabled = false

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/FLP32-C.+Prevent+or+detect+domain+and+range+errors+in+math+functions"
cwe = ["CWE-682", "CWE-391"]
