-- Schema-only DDL for the Postgres benchmark DB (task 638,
-- BENCHMARK_POSTGRES_MIGRATION_PLAN.md §2/§4). No indexes here on purpose --
-- building 13 indexes against a 24M-row bulk load is the single biggest
-- avoidable cost (see 02_indexes.sql, applied after 03_load.sh).
--
-- Mapping applied throughout (plan §2):
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--     (BY DEFAULT, not ALWAYS -- the load inserts explicit ids to preserve FKs)
--   REAL                              -> DOUBLE PRECISION
--   booleans (in_bad_section, is_cwe_matched, requires_manual_review, ...) stay INTEGER
--   ISO timestamp columns (started_at, scanned_at, adjudicated_at, ...) stay TEXT
-- Deliberately NOT done here (plan §8, out of scope for this migration):
--   converting timestamps to timestamptz or booleans to BOOLEAN

CREATE TABLE runs (
    run_id          TEXT PRIMARY KEY,
    sqc_version     TEXT NOT NULL,
    commit_sha      TEXT NOT NULL,
    mode            TEXT NOT NULL DEFAULT 'fast',
    status          TEXT NOT NULL DEFAULT 'running',
    started_at      TEXT NOT NULL,
    finished_at     TEXT,
    pid             INTEGER,
    jobs            INTEGER,
    total_cwes      INTEGER,
    hostname        TEXT,
    cpu_model       TEXT,
    cpu_cores       INTEGER,
    ram_gb          DOUBLE PRECISION,
    os_version      TEXT,
    cache_state     TEXT NOT NULL DEFAULT 'cold'
);

CREATE TABLE cwe_scans (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          TEXT NOT NULL REFERENCES runs(run_id),
    cwe_id          TEXT NOT NULL,
    cwe_dir_name    TEXT NOT NULL,
    file_count      INTEGER DEFAULT 0,
    violation_count INTEGER DEFAULT 0,
    duration_s      DOUBLE PRECISION,
    status          TEXT NOT NULL DEFAULT 'pending',
    UNIQUE(run_id, cwe_dir_name)
);

CREATE TABLE violations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cwe_scan_id     BIGINT NOT NULL REFERENCES cwe_scans(id),
    rule_id         TEXT NOT NULL,
    file_path       TEXT NOT NULL,
    line            INTEGER NOT NULL,
    classification  TEXT,
    in_bad_section  INTEGER DEFAULT 0,
    in_good_section INTEGER DEFAULT 0,
    hits_flaw_line  INTEGER DEFAULT 0,
    is_cwe_matched  INTEGER DEFAULT 0
);

CREATE TABLE cwe_metrics (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cwe_scan_id             BIGINT NOT NULL UNIQUE REFERENCES cwe_scans(id),
    tp_count                INTEGER DEFAULT 0,
    fp_count                INTEGER DEFAULT 0,
    tp_rate_pct             DOUBLE PRECISION DEFAULT 0,
    flaw_lines_total        INTEGER DEFAULT 0,
    flaw_lines_detected     INTEGER DEFAULT 0,
    flaw_detection_rate_pct DOUBLE PRECISION DEFAULT 0,
    cwe_matched_tp          INTEGER DEFAULT 0,
    cwe_matched_fp          INTEGER DEFAULT 0,
    noise_count             INTEGER DEFAULT 0,
    noise_ratio             DOUBLE PRECISION DEFAULT 0,
    per_file_detected       INTEGER DEFAULT 0,
    per_file_total          INTEGER DEFAULT 0,
    per_file_rate           DOUBLE PRECISION DEFAULT 0,
    flaw_hit_detected       INTEGER DEFAULT 0,
    flaw_hit_total          INTEGER DEFAULT 0,
    flaw_hit_rate           DOUBLE PRECISION DEFAULT 0
);

CREATE TABLE rule_cwe_breakdown (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cwe_scan_id     BIGINT NOT NULL REFERENCES cwe_scans(id),
    rule_id         TEXT NOT NULL,
    tp_count        INTEGER DEFAULT 0,
    fp_count        INTEGER DEFAULT 0,
    flaw_line_count INTEGER DEFAULT 0,
    is_cwe_matched  INTEGER DEFAULT 0,
    UNIQUE(cwe_scan_id, rule_id)
);

CREATE TABLE realworld_runs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sqc_version     TEXT NOT NULL,
    commit_sha      TEXT,
    scanned_at      TEXT,
    hostname        TEXT,
    cpu_model       TEXT,
    cpu_cores       INTEGER,
    notes           TEXT,
    UNIQUE(sqc_version, commit_sha)
);

CREATE TABLE realworld_results (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          BIGINT NOT NULL REFERENCES realworld_runs(id),
    project         TEXT NOT NULL,
    tool            TEXT NOT NULL,
    c_files         INTEGER DEFAULT 0,
    loc             INTEGER DEFAULT 0,
    violation_count INTEGER DEFAULT 0,
    duration_s      DOUBLE PRECISION,
    codebase_commit TEXT,
    UNIQUE(run_id, project, tool)
);

CREATE TABLE realworld_violations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id       BIGINT NOT NULL REFERENCES realworld_results(id),
    rule_id         TEXT NOT NULL,
    file_path       TEXT NOT NULL,
    line            INTEGER NOT NULL,
    column_num      INTEGER DEFAULT 0,
    severity        TEXT,
    message         TEXT,
    suggestion      TEXT,
    requires_manual_review INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE ground_truth (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project         TEXT NOT NULL,
    codebase_commit TEXT NOT NULL,
    file_path       TEXT NOT NULL,
    line            INTEGER NOT NULL,
    rule_id         TEXT NOT NULL,
    verdict         TEXT NOT NULL,           -- 'TP' | 'FP' | 'uncertain'
    adjudicator     TEXT,                    -- 'manual', 'claude-opus-4.8', ...
    reason          TEXT,
    source          TEXT,                    -- provenance, e.g. 'precision_audit_0.4.22'
    adjudicated_at  TEXT NOT NULL,
    provenance      TEXT,
    confidence      TEXT,
    UNIQUE(project, codebase_commit, file_path, line, rule_id)
);

CREATE TABLE audited_files (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project         TEXT NOT NULL,
    codebase_commit TEXT NOT NULL,
    file_path       TEXT NOT NULL,           -- project-relative
    adjudicator     TEXT,
    audited_at      TEXT NOT NULL,
    n_findings      INTEGER DEFAULT 0,       -- sqc findings in this file (precision denom)
    n_tp            INTEGER DEFAULT 0,
    n_fp            INTEGER DEFAULT 0,
    n_uncertain     INTEGER DEFAULT 0,
    n_fn            INTEGER DEFAULT 0,       -- real bugs sqc missed (recall)
    notes           TEXT,
    UNIQUE(project, codebase_commit, file_path)
);

CREATE TABLE audit_corpus_meta (
    project             TEXT NOT NULL,
    codebase_commit     TEXT NOT NULL,
    total_inscope_files INTEGER,
    scope_note          TEXT,
    updated_at          TEXT,
    PRIMARY KEY (project, codebase_commit)
);

CREATE TABLE oracle_versions (
    version         TEXT PRIMARY KEY,
    frozen_at       TEXT NOT NULL,
    notes           TEXT,
    snapshot_json   TEXT
);
