-- Restricted role for nodes that RUN benchmarks (the Juliet/real-world
-- runners via bench/db.py), as opposed to sqc_migrate (this migration's
-- owner role) or a human adjudication workflow. Per task 638's original
-- intent: no DROP, no write on ground_truth (the 88,939-row irreplaceable
-- oracle). Password is set separately -- see the accompanying shell step.
--
-- One correction versus task 638's original wording: DELETE is required,
-- not just INSERT/SELECT. bench/db.py's runner deletes stale child rows on
-- a resumed/re-ingested scan (violations/cwe_metrics/rule_cwe_breakdown on
-- CWE-scan resume; realworld_violations on realworld re-ingest) before
-- re-inserting -- confirmed by reading every DELETE/UPDATE site in
-- bench/db.py before writing these grants, not by re-deriving the original
-- task note.
--
-- ground_truth, audited_files, audit_corpus_meta, oracle_versions are all
-- written only by the adjudication/oracle-management workflow (import_labels,
-- freeze_oracle_version, etc.) -- never by the automated runner -- so the
-- writer role gets SELECT only there (realworld-score's join still works).

-- CREATE ROLE requires superuser -- run separately as the postgres role
-- (see 05a_create_writer_role.sh). This file does the grants, run as
-- sqc_migrate (owner of every table below).

GRANT CONNECT ON DATABASE sqc_bench TO sqc_writer;
GRANT USAGE ON SCHEMA public TO sqc_writer;

GRANT SELECT, INSERT, UPDATE, DELETE ON
    runs,
    cwe_scans,
    violations,
    cwe_metrics,
    rule_cwe_breakdown,
    realworld_runs,
    realworld_results,
    realworld_violations
TO sqc_writer;

GRANT SELECT ON
    ground_truth,
    audited_files,
    audit_corpus_meta,
    oracle_versions
TO sqc_writer;

-- Identity columns (GENERATED BY DEFAULT AS IDENTITY) don't need an explicit
-- sequence GRANT for a role that already has table INSERT -- Postgres
-- checks table privilege, not nextval() privilege, for identity columns.
