-- Task 637: calibration_labels, added alongside ground_truth so a second,
-- independent verdict can be recorded against a finding ground_truth already
-- labels -- without touching ground_truth's UNIQUE(project, codebase_commit,
-- file_path, line, rule_id), which every existing precision/recall query
-- depends on staying one-row-per-finding. Mirrors bench/db.py's SQLite
-- _SCHEMA definition; apply this manually against the shared Postgres
-- instance (sqc_migrate role) the same way 01_schema.sql/02_indexes.sql
-- were applied for task 638 -- it is not run automatically.

CREATE TABLE calibration_labels (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gt_id                BIGINT NOT NULL REFERENCES ground_truth(id),
    project              TEXT NOT NULL,
    codebase_commit      TEXT NOT NULL,
    file_path            TEXT NOT NULL,
    line                 INTEGER NOT NULL,
    rule_id              TEXT NOT NULL,
    verdict              TEXT NOT NULL,
    adjudicator          TEXT NOT NULL,
    reason               TEXT,
    source               TEXT,
    adjudicated_at       TEXT NOT NULL,
    original_verdict     TEXT NOT NULL,
    original_adjudicator TEXT,
    UNIQUE(gt_id, adjudicator)
);
CREATE INDEX idx_calib_lookup ON calibration_labels(rule_id, project);

-- If the writer role from 05_writer_role.sql is in use: calibration_labels
-- is an adjudication-workflow table like ground_truth itself, so it should
-- get the same SELECT-only grant there, not the runner's write access.
-- GRANT SELECT ON calibration_labels TO sqc_bench_writer;
