-- Restricted role for a HUMAN adjudication session (ground-truth labeling,
-- delta-adjudication, and now task 637's calibration rounds), as opposed to
-- sqc_writer (the automated benchmark runner, deliberately denied write
-- access to the oracle -- see 05_writer_role.sql) or sqc_migrate (schema
-- owner, used for DDL only).
--
-- Filed because task 637's calibration-import needs INSERT on ground_truth's
-- new calibration_labels side table, and sqc_writer's own migration
-- explicitly argues that access should NOT go to the runner role. Rather
-- than widen sqc_writer and quietly erode that boundary, this is a distinct
-- credential (separate DSN) for whoever is actively running an adjudication
-- workflow -- so an automated benchmark run still cannot touch the oracle,
-- but a person doing labeling work can.
--
-- Scope: write access ONLY to the oracle tables the adjudication CLI
-- commands (realworld-import-labels, calibration-import, and any future
-- freeze_oracle_version tooling) actually touch. No DELETE -- every existing
-- write path is append-or-update (insert_ground_truth_labels's on_conflict,
-- insert_calibration_labels's skip-if-exists, freeze_oracle_version's
-- INSERT). Everything else (runs/violations/etc.) stays SELECT-only, same
-- as sqc_writer's boundary in reverse -- an adjudication session has no
-- business touching benchmark-run bookkeeping either.
--
-- CREATE ROLE requires superuser -- run separately as the postgres role,
-- same as 05_writer_role.sql's counterpart step:
--   sudo -u postgres psql -d sqc_bench -c \
--     "CREATE ROLE sqc_adjudicate LOGIN PASSWORD '<set one>';"
-- This file does the grants, run as sqc_migrate (owner of every table
-- below).

GRANT CONNECT ON DATABASE sqc_bench TO sqc_adjudicate;
GRANT USAGE ON SCHEMA public TO sqc_adjudicate;

GRANT SELECT, INSERT, UPDATE ON
    ground_truth,
    calibration_labels,
    audited_files,
    audit_corpus_meta,
    oracle_versions
TO sqc_adjudicate;

GRANT SELECT ON
    runs,
    cwe_scans,
    violations,
    cwe_metrics,
    rule_cwe_breakdown,
    realworld_runs,
    realworld_results,
    realworld_violations
TO sqc_adjudicate;

-- Identity columns (GENERATED BY DEFAULT AS IDENTITY) don't need an explicit
-- sequence GRANT for a role that already has table INSERT -- Postgres
-- checks table privilege, not nextval() privilege, for identity columns.
