[metadata]
id = "MSC40-C"
type = "rule"
category = "MSC"
number = 40
title = "Do not violate constraints"
description = """
According to the C Standard, 3.8 [ISO/IEC 9899:2011], a constraint is a
"restriction, either syntactic or semantic, by which the exposition of language
elements is to be interpreted." Despite the similarity of the terms, a runtime
constraint is not a kind of constraint. Violating anyshallstatement within a
constraint clause in the C Standard requires animplementationto issue a
diagnostic message, the C Standard, 5.1.1.3 [ISO/IEC 9899:2011] states The C
Standard further explains in a footnote
"""
severity = "Low"
likelihood = "Unlikely"
priority = "P1"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "Unknown"

[rules.cert_c.MSC40-C]
enabled = false

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/MSC40-C.+Do+not+violate+constraints"
