[metadata]
id = "STR37-C"
type = "recommendation"
category = "STR"
number = 37
title = "Arguments to character-handling functions must be representable as an unsigned char"
description = """
According to the C Standard, 7.4.1 paragraph 1 [ISO/IEC 9899:2024], See
alsoundefined behavior 112. This rule is applicable only to code that runs on
platforms where thechardata type is defined to have the same range,
representation, and behavior assigned char.
"""
severity = "Low"
likelihood = "Unlikely"
priority = "P3"
level = "L3"
cert_version = "2016 Edition (Wiki)"
last_modified = "Aug 06, 2025"

[rules.cert_c.STR37-C]
enabled = true

[references]
wiki = "https://wiki.sei.cmu.edu/confluence/display/c/STR37-C.+Arguments+to+character-handling+functions+must+be+representable+as+an+unsigned+char"
cwe = ["CWE-704", "CWE-686", "CWE-683"]
